[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "arche-act"
version = "0.1.1"
authors = ["baidu.com"]
description = "Communicative Agents with Disambiguation and Polymorphic Role-Playing"
readme = "README.md"
keywords = [
    "communicative-ai",
    "artificial-intelligence",
    "deep-learning",
    "multi-agent-systems",
    "cooperative-ai",
    "natural-language-processing",
    "large-language-models",
    "travel-assistant",
]
license = "Apache License 2.0"
homepage = "https://www.baidu.com/"
repository = "https://github.com/PaddlePaddle/PaddleSpatial/tree/main/apps/arche-act"
documentation = "https://docs.baidu.com/arche-act"

[tool.poetry.dependencies]
python = "^3.8.1"
numpy = "^1"
openai = "^0"
tenacity = "^8"
tiktoken = "^0"
colorama = "^0"
jsonschema = "^4"
types-colorama = "^0"
types-requests = "^2"
bs4 = "^0"
protobuf = "^4"
docx2txt = "^0.8" 
PyMuPDF = "^1.22.5"  
pathlib = "^1.0.1"
loguru = "^0.7.2"

transformers = { version = "^4", optional = true }
diffusers = { version = "^0", optional = true }
accelerate = { version = "^0", optional = true }
datasets = { version = "^2", optional = true }
torch = { version = "^1", optional = true }
soundfile = { version = "^0", optional = true }
sentencepiece = { version = "^0", optional = true }
opencv-python = { version = "^4", optional = true }
wikipedia = { version = "^1", optional = true }

[tool.poetry.extras]
huggingface-agent = [
    "transformers",
    "diffusers",
    "accelerate",
    "datasets",
    "torch",
    "soundfile",
    "sentencepiece",
    "opencv-python",
    "wikipedia",
]

all = [
    "transformers",
    "diffusers",
    "accelerate",
    "datasets",
    "torch",
    "soundfile",
    "sentencepiece",
    "opencv-python",
    "wikipedia",
]

[tool.poetry.group.dev]
optional = true
[tool.poetry.group.dev.dependencies]
yapf = "0.32.0"
isort = "5.12.0"
flake8 = "4.0.1"
mypy = "^1.5.1"
toml = ">=0.10.2"
pre-commit = "^3"
pytest = "^7"
pytest-cov = "^4"
gradio = "^4"
mock = "^5"

[tool.poetry.group.docs]
optional = true
[tool.poetry.group.docs.dependencies]
sphinx = "^6"
sphinx_book_theme = "*"
recommonmark = "*"

[tool.yapf]
based_on_style = "pep8"
split_before_named_assigns = false

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
skip = [".gitingore", "__init__.py"]

[tool.pytest.ini_options]
pythonpath = ["."]
addopts = ["--strict-markers"]
markers = [
    "very_slow: mark a very slow test to run only in full test mode",
    "model_backend: for tests that require OpenAI API key or a local LLM",
]

[tool.coverage.report]
include_namespace_packages = true

[[tool.mypy.overrides]]
module = [
    "transformers.*",
    "packaging.*",
    "tiktoken",
    "openai",
    "openai.error",
    "tenacity",
    "tenacity.stop",
    "tenacity.wait",
    "pytest",
    "_pytest.config",
    "_pytest.nodes",
    "numpy",
    "torch",
    "sqlalchemy",
    "google.cloud.sql.connector",
    "gradio",
    "database_connection",
    "huggingface_hub",
    "huggingface_hub.utils._errors",
    "wikipedia",
    "jsonschema.*",
    "bs4.*",
    "docx2txt",
    "PyMuPDF",
    "fitz"
]
ignore_missing_imports = true
